title: Ohjelmistotuotanto avoin yliopisto 2022
email: matti.luukkainen@helsinki.fi
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ohjelmistotuotanto-hy-avoin.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mluukkai
repo_url: "https://github.com/ohjelmistotuotanto-hy-avoin/ohjelmistotuotanto-hy-avoin.github.io"
repo_branch: "master"
stats_url: "https://study.cs.helsinki.fi/stats/courses/ohtu-avoin-2022"
python_exercise_repo_url: "https://github.com/ohjelmistotuotanto-hy-avoin/python-kevat-2022"
java_exercise_repo_url: "https://github.com/ohjelmistotuotanto-hy-avoin/java-kevat-2022"
miniproject_enrollment_url: "https://study.cs.helsinki.fi/assembler/course/725fb26a-9fda-48e6-80cd-6a01cb9db2c9"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
